#!/bin/bash
#shell script to run to install alt managaer
#To send alerts, we're going to use Alertmanager. It takes care of deduplicating, grouping, and routing them to the correct receiver integration such as email, PagerDuty, or in our case Slack. You can set up multiple Alertmanagers to achieve high availability. For this demo, I will install a single one.
#reate a system user for Alertmanager
sudo useradd \
    --system \
    --no-create-home \
    --shell /bin/false alertmanager
#download Alertmanager
wget https://github.com/prometheus/alertmanager/releases/download/v0.23.0/alertmanager-0.23.0.linux-amd64.tar.gz
#Extract Alertmanager
tar -xvf alertmanager-0.23.0.linux-amd64.tar.gz
#Alertmanager, we need storage. It is mandatory (it defaults to "data/") and is used to store Alertmanager's notification states and silences. Without this state (or if you wipe it), Alertmanager would not know across restarts what silences were created or what notifications were already sent
sudo mkdir -p /alertmanager-data /etc/alertmanager
# move Alermanager's binary to the local bin and copy sample config
sudo mv alertmanager-0.23.0.linux-amd64/alertmanager /usr/local/bin/
sudo mv alertmanager-0.23.0.linux-amd64/alertmanager.yml /etc/alertmanager/
#Remove downloaded archive
rm -rf alertmanager*
#we can run Alertmanager.
alertmanager --version
if [ $? = "0" ];
then 
echo 'build succesfull'
else
echo 'build unsuccesfull'
fi 
echo '**************'
echo '**check status in version***'
echo 'run bellow commands'
echo sudo vim /etc/systemd/system/alertmanager.service
echo '**************'
echo sudo systemctl start alertmangaer
echo sudo systemctl enable alertmanager
echo sudo systemctl start alertmanager
echo sudo systemctl status alertmanager
echo 'urun above commands'
