#!/bin/bash

# Check if the script is being run as root

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root."
   exit 1
fi

# Install all the dependenices

sudo apt-get install -y apt-transport-https software-properties-common

# Add GPG key

wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -

# adding it to repsitory for stability

echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

# Update & Install Grafana

sudo apt-get update
sudo apt-get -y install grafana

# To automatically start the Grafana after reboot, enable the service.

sudo systemctl enable grafana-server

# To check start the service

sudo systemctl start grafana-server

# To check the Status of the service

sudo systemctl status grafana-server
